name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Image tag
      run:  |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd angular
        docker build . --file Dockerfile --tag ghcr.io/bokamatyas/library-inventory-angular:$IMAGE_TAG --tag ghcr.io/bokamatyas/library-inventory-angular:latest
        docker login ghcr.io --username bokamatyas --password ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/bokamatyas/library-inventory-angular:$IMAGE_TAG
        docker push ghcr.io/bokamatyas/library-inventory-angular:latest
